Distributions = Distributions or {};

local distributionTable = {

	AmmoCan762 = {
			rolls = 2,
			items = {
					"762Box", 100,
					"762Box", 50,
					"762Box", 25,
					"762Box", 10,
					"762Box", 5,
			},
			fillRand = 0,
	},

	AmmoCan308 = {
			rolls = 2,
			items = {
				"308Box", 100,
				"308Box", 50,
				"308Box", 25,
				"308Box", 10,
				"308Box", 5,
			},
			fillRand = 0,
	},

	AmmoCan556 = {
			rolls = 2,
			items = {
					"556Box", 100,
					"556Box", 50,
					"556Box", 25,
					"556Box", 10,
					"556Box", 5,
			},
			fillRand = 0,
	},

	AmmoCan9mm = {
			rolls = 2,
			items = {
				"Bullets9mmBox", 100,
				"Bullets9mmBox", 50,
				"Bullets9mmBox", 25,
				"Bullets9mmBox", 10,
				"Bullets9mmBox", 5,
			},
			fillRand = 0,
	},

	--	gunstore
	gunstore = {

		counter = {
			rolls = 1,
			items = {
				"Base.45Silencer",			0.2,
				"Base.9mmSilencer",			0.25,
				"Base.223Silencer",			0.15,
				"Base.308Silencer",			0.15,
				"Base.Sling", 5,
	      "Base.Sling_Leather",     5,
				"Base.IronSight",			5,
				"Base.RedDot",			2,
				"Base.x2Scope",			1,
	      "Base.x4Scope",       0.5,
	      "Base.x8Scope",    0.5,
				"Base.Laser",				2,
				"Base.ChokeTubeFull",				2,
				"Base.ChokeTubeImproved",				1,
				"Base.TacticalStock",			1,
	      "Base.ShotgunStock",       1,
	      "Base.LightShotgunStock",    1,
				"Base.AmmoStock",			1,
				"Base.RecoilPad",			2,
				"Base.ExtendedRecoilPad",    1,
				"Base.Rifle_Bipod",			1,
				"Base.9mmCompensator",			1,
				"Base.MP5Mag",			1,
				"Base.223Clip",			1,
				"Base.Glock17Mag",				1,
				"Base.FN_FAL_Mag",				1,
				"Base.556Clip",			0.5,
				"Base.556Box",			1,
				"Base.4440Box",		2,
				"Base.762Box",		2,
				"Base.223Box",		2,
				"Base.308Box",		2,
				"Base.22LRBox",          5,
				"Base.Bullets38Box",		2,
				"Base.Bullets44Box",		2,
				"Base.Bullets45Box",		2,
				"Base.Bullets9mmBox",		2,
				"Base.ShotgunShellsBox",				5,
				"Base.GunToolKit",				2,
			},
		},

		displaycase = {
			rolls = 1,
			items = {
				"Base.Pistol",					1,
				"Base.Pistol2",				1,
				"Base.Pistol3",					1,
				"Base.Glock17",				1,
				"Base.Glock17Mag",				1,
				"Base.223Clip",				1,
				"Base.ColtPeacemaker",				1,
				"Base.Revolver",				1,
				"Base.Revolver_Long",				1,
				"Base.Revolver_Short",				1,
				"Base.Shotgun",				1,
				"Base.DoubleBarrelShotgun",				1,
				"Base.Remington870Wood",				1,
				"Base.Mossberg500",			0.5,
				"Base.Mossberg500Tactical",			0.5,
				"Base.UZI", 		0.5,
				"Base.FN_FAL", 		0.5,
				"Base.MP5",		0.5,
				"Base.Winchester94", 				0.5,
				"Base.Winchester73",			0.5,
				"Base.4440Box",		2,
				"Base.Bullets38Box",		2,
				"Base.Bullets44Box",		2,
				"Base.Bullets45Box",		2,
				"Base.Bullets9mmBox",		2,
				"Base.22LRBox",          5,
				"Base.ShotgunShellsBox",				5,
			},
		},

		locker ={
			rolls = 2,
			items = {
				"Base.DoubleBarrelShotgun",			2,
				"Base.Shotgun",		3,
				"Base.Mossberg500",			3,
				"Base.Mossberg500Tactical",			3,
				"Base.Winchester94",			2,
				"Base.Winchester73",				2,
				"Base.HuntingRifle",			3,
				"Base.Rugerm7722",			3,
				"Base.VarmintRifle",			2,
				"Base.223Clip",			2,
				"Base.M24Rifle",			0.5,
				"Base.FN_FAL", 		0.5,
				"Base.AssaultRifle",			0.1,
				"Base.556Clip",		2,
				"Base.556Box",			1,
				"Base.4440Box",		2,
				"Base.762Box",		2,
				"Base.223Box",		2,
				"Base.308Box",		2,
				"Base.22LRBox",          5,
				"Base.ShotgunShellsBox",				5,
				"Base.Sling", 5,
	      "Base.Sling_Leather",     5,
				"Base.IronSight",			5,
				"Base.RedDot",			2,
				"Base.x2Scope",			1,
	      "Base.x4Scope",       0.5,
	      "Base.x8Scope",    0.5,
				"Base.Laser",				2,
				"Base.ChokeTubeFull",				2,
				"Base.ChokeTubeImproved",				1,
				"Base.TacticalStock",			1,
	      "Base.ShotgunStock",       1,
	      "Base.LightShotgunStock",    1,
				"Base.AmmoStock",			1,
				"Base.RecoilPad",			2,
				"Base.ExtendedRecoilPad",    1,
				"Base.Rifle_Bipod",			1,
				"Base.9mmCompensator",			1,
				"Base.45Silencer",			0.2,
				"Base.9mmSilencer",			0.25,
				"Base.223Silencer",			0.15,
				"Base.308Silencer",			0.15,
				"Base.GunToolKit",				5,
			},
		},

	        shelves = {
			rolls = 3,
			items = {
			"Base.Sling", 5,
			"Base.Sling_Leather",     5,
			"Base.RecoilPad",			2,
			"Base.ExtendedRecoilPad",    1,
			"Base.Rifle_Bipod",			1,
			"Base.9mmCompensator",			1,
			"Base.GunToolKit",				1,
			},
		},

		metal_shelves = {
			rolls = 3,
			items = {
				"Base.556Box",			1,
				"Base.4440Box",		1,
				"Base.762Box",		1,
				"Base.223Box",		1,
				"Base.308Box",		1,
				"Base.22LRBox",          5,
				"Base.Bullets38Box",		4,
				"Base.Bullets44Box",		3,
				"Base.Bullets45Box",		4,
				"Base.Bullets9mmBox",		4,
				"Base.ShotgunShellsBox",				5,
				"Base.GunToolKit",				1,
			},
		},
	},

--Gunstore Storage
	gunstorestorage = {

		crate = {
			rolls = 1,
			items = {
				"Base.MP5Mag",			1,
				"Base.Glock17Mag",				2,
				"Base.556Clip",			1,
				"Base.223Clip",			1,
				"Base.Glock17",				1,
				"Base.UZI", 		1,
				"Base.MP5",		2,
				"Base.FN_FAL", 		1,
				"Base.FN_FAL_Mag", 		0.5,
				"Base.AssaultRifle",		1,
				"Base.M24Rifle",		1,
				"Base.M60",		0.5,
				"Base.GunToolKit",				3,
				"Base.556Box",			1,
				"Base.4440Box",		1,
				"Base.762Box",		1,
				"Base.223Box",		1,
				"Base.308Box",		1,
				"Base.22LRBox",          5,
				"Base.Bullets38Box",		4,
				"Base.Bullets44Box",		3,
				"Base.Bullets45Box",		4,
				"Base.Bullets9mmBox",		4,
				"Base.ShotgunShellsBox",				5,
				"Base.AmmoCan762",		0.5,
				"Base.AmmoCan556",		0.5,
				"Base.AmmoCan308",		0.5,
				"Base.AmmoCan9mm",		1,
				"Base.Sling", 5,
	      "Base.Sling_Leather",     5,
				"Base.IronSight",			5,
				"Base.RedDot",			2,
				"Base.x2Scope",			1,
	      "Base.x4Scope",       0.5,
	      "Base.x8Scope",    0.5,
				"Base.Laser",				2,
				"Base.ChokeTubeFull",				2,
				"Base.ChokeTubeImproved",				1,
				"Base.TacticalStock",			1,
	      "Base.ShotgunStock",       1,
	      "Base.LightShotgunStock",    1,
				"Base.AmmoStock",			1,
				"Base.RecoilPad",			2,
				"Base.ExtendedRecoilPad",    1,
				"Base.Rifle_Bipod",			1,
				"Base.9mmCompensator",			1,
				"Base.45Silencer",			0.2,
				"Base.9mmSilencer",			0.25,
				"Base.223Silencer",			0.15,
				"Base.308Silencer",			0.15,
				"Base.GunToolKit",				5,
			},
		},

		locker ={
			rolls = 3,
			items = {
			"Base.MP5Mag",			1,
			"Base.Glock17Mag",				2,
			"Base.223Clip",				1,
			"Base.556Clip",			1,
			"Base.Glock17",				1,
			"Base.UZI", 		1,
			"Base.MP5",		2,
			"Base.FN_FAL", 		0.5,
			"Base.FN_FAL_Mag", 		0.5,
			"Base.AssaultRifle",		1,
			"Base.M24Rifle",		1,
			"Base.M60",		0.25,
			"Base.GunToolKit",				3,
			"Base.AmmoCan762",		0.5,
			"Base.AmmoCan556",		0.5,
			"Base.AmmoCan308",		0.5,
			"Base.AmmoCan9mm",		1,
			},
		},

		metal_shelves = {
			rolls = 3,
			items = {
				"Base.556Box",			1,
				"Base.762Box",		1,
				"Base.AmmoCan762",		0.5,
				"Base.AmmoCan556",		0.5,
				"Base.AmmoCan308",		0.5,
				"Base.AmmoCan9mm",		1,
				"Base.22LRBox",          5,
				"Base.Bullets9mmBox",		4,
				"Base.GunToolKit",				1,
			},
		},
	},

--Police Storage
	policestorage = {
		counter = {
			rolls = 3,
			items = {
				"Base.GunToolKit",				5,
			},
		},

		locker = {
			rolls = 3,
			items = {
				"Base.Remington870Wood",		4,
				"Base.Mossberg590",     4,
				"Base.Mossberg500Tactical", 4,
				"Base.Glock17",	2,
				"Base.Glock17Mag",			3,
				"Base.AssaultRifle",			0.5,
				"Base.M16A2",					0.5,
				"Base.556Clip",		2,
				"Base.M24Rifle",			0.1,
				"Base.VarmintRifle",			1,
	      "Base.MP5",       0.5,
	      "Base.MP5Mag",      2,
	      "Base.223Clip",      2,
				"Base.556Box",			1,
				"Base.4440Box",		1,
				"Base.762Box",		1,
				"Base.223Box",		1,
				"Base.308Box",		1,
				"Base.22LRBox",          5,
				"Base.Bullets38Box",		4,
				"Base.Bullets44Box",		3,
				"Base.Bullets45Box",		4,
				"Base.Bullets9mmBox",		4,
				"Base.ShotgunShellsBox",				5,
				"Base.GunToolKit",				5,
				"Base.45Silencer",			0.2,
				"Base.9mmSilencer",			0.25,
				"Base.223Silencer",			0.15,
				"Base.308Silencer",			0.15,
			},
		},
		metal_shelves = {
			rolls = 3,
			items = {
				"Base.556Box",			1,
				"Base.4440Box",		1,
				"Base.762Box",		1,
				"Base.223Box",		1,
				"Base.308Box",		1,
				"Base.22LRBox",          5,
				"Base.Bullets38Box",		4,
				"Base.Bullets44Box",		3,
				"Base.Bullets45Box",		4,
				"Base.Bullets9mmBox",		4,
				"Base.ShotgunShellsBox",				5,
				"Base.AmmoCan762",		0.5,
				"Base.AmmoCan556",		0.5,
				"Base.AmmoCan308",		0.5,
				"Base.AmmoCan9mm",		1,
	      "Base.Sling", 5,
				"Base.IronSight",			5,
				"Base.RedDot",			2,
				"Base.x2Scope",			1,
	      "Base.x4Scope",       0.5,
	      "Base.x8Scope",    0.5,
	      "Base.x4-x12Scope",          1,
				"Base.Laser",				2,
				"Base.ChokeTubeFull",				2,
				"Base.ChokeTubeImproved",				1,
				"Base.TacticalStock",			1,
	      "Base.ShotgunStock",       1,
	      "Base.LightShotgunStock",    1,
				"Base.AmmoStock",			1,
				"Base.RecoilPad",			2,
				"Base.ExtendedRecoilPad",    1,
				"Base.Rifle_Bipod",			1,
				"Base.9mmCompensator",			1,
				"Base.9mmSilencer",			0.25,
				"Base.223Silencer",			0.15,
				"Base.308Silencer",			0.15,
				"Base.GunToolKit",				5,
			},
		},
		filingcabinet = {
			rolls = 1,
			items = {
			},
		},
		crate = {
			rolls = 3,
			items = {
			},
		},
	},
	-- Army storage
	armystorage = {

		locker = {
			rolls = 3,
			items = {
				"Base.Pistol",					1,
				"Base.Remington870Wood",				1,
				"Base.Mossberg500",			0.5,
				"Base.Mossberg500Tactical",			0.5,
				"Base.MP5",		0.5,
				"Base.Bullets38Box",		2,
				"Base.Bullets44Box",		2,
				"Base.Bullets45Box",		2,
				"Base.Bullets9mmBox",		2,
				"Base.22LRBox",          5,
				"Base.ShotgunShellsBox",				5,
				"Base.AmmoCan762",		0.5,
				"Base.AmmoCan556",		0.5,
				"Base.AmmoCan308",		0.5,
				"Base.AmmoCan9mm",		1,
				"Base.Shotgun",		3,
				"Base.Mossberg500",			3,
				"Base.Mossberg500Tactical",			3,
				"Base.M24Rifle",			1,
				"Base.M60",		0.5,
				"Base.FN_FAL", 		1,
				"Base.AssaultRifle",			1,
				"Base.AssaultRifle2",			0.5,
				"Base.M16A2",					1,
				"Base.Sling_Camo",		5,
	      "Base.Sling_Olive", 5,
				"Base.IronSight",			5,
				"Base.RedDot",			2,
				"Base.x2Scope",			1,
	      "Base.x4Scope",       0.5,
	      "Base.x8Scope",    0.5,
	      "Base.x4-x12Scope",          1,
				"Base.Laser",				2,
				"Base.ChokeTubeFull",				2,
				"Base.ChokeTubeImproved",				1,
				"Base.TacticalStock",			1,
	      "Base.ShotgunStock",       1,
	      "Base.LightShotgunStock",    1,
				"Base.AmmoStock",			1,
				"Base.RecoilPad",			2,
				"Base.ExtendedRecoilPad",    1,
				"Base.Rifle_Bipod",			1,
				"Base.9mmCompensator",			1,
				"Base.45Silencer",			0.2,
				"Base.9mmSilencer",			0.25,
				"Base.223Silencer",			0.15,
				"Base.308Silencer",			0.15,
				"Base.GunToolKit",				5,
			},
		},

		metal_shelves = {
			rolls = 2,
			items = {
				"Base.556Clip",		1,
				"Base.9mmClip",		2,
				"Base.MP5Mag",		2,
				"Base.223Clip",		2,
				"Base.FN_FAL_Mag",		2,
				"Base.M60Mag",		2,
				"Base.556Box",			1,
				"Base.762Box",		1,
				"Base.22LRBox",          5,
				"Base.Bullets45Box",		4,
				"Base.Bullets9mmBox",		4,
				"Base.ShotgunShellsBox",				5,
				"Base.AmmoCan762",		0.5,
				"Base.AmmoCan556",		0.5,
				"Base.AmmoCan308",		0.5,
				"Base.AmmoCan9mm",		1,
				"Base.GunToolKit",				5,
			},
		},

		crate = {
			rolls = 1,
			items = {
			"Base.556Clip",		1,
			"Base.9mmClip",		2,
			"Base.MP5Mag",		2,
			"Base.223Clip",		2,
			"Base.FN_FAL_Mag",		2,
			"Base.M60Mag",		1,
			"Base.556Box",			1,
			"Base.762Box",		1,
			"Base.22LRBox",          6,
			"Base.Bullets45Box",		4,
			"Base.Bullets9mmBox",		4,
			"Base.ShotgunShellsBox",				5,
			"Base.AmmoCan762",		0.5,
			"Base.AmmoCan556",		0.5,
			"Base.AmmoCan308",		0.5,
			"Base.AmmoCan9mm",		1,
			"Base.GunToolKit",				5,
			},
		},
	},
	armyhanger = {
		metal_shelves = {
			rolls = 1,
			items = {
			"Base.Sling_Camo",		5,
			"Base.Sling_Olive", 5,
			"Base.IronSight",			5,
			"Base.RedDot",			2,
			"Base.x2Scope",			1,
			"Base.x4Scope",       0.5,
			"Base.x8Scope",    0.5,
			"Base.x4-x12Scope",          1,
			"Base.Laser",				2,
			"Base.ChokeTubeFull",				2,
			"Base.ChokeTubeImproved",				1,
			"Base.TacticalStock",			1,
			"Base.ShotgunStock",       1,
			"Base.LightShotgunStock",    1,
			"Base.AmmoStock",			1,
			"Base.RecoilPad",			2,
			"Base.ExtendedRecoilPad",    1,
			"Base.Rifle_Bipod",			1,
			"Base.9mmCompensator",			1,
			"Base.GunToolKit",				5,
			},
		},
	},

	security = {
		counter = {
			rolls = 3,
			items = {
			"Base.Pistol",					1,
			"Base.Pistol2",				1,
			"Base.Pistol3",					1,
			"Base.Glock17",				1,
			"Base.Glock17Mag",				1,
			"Base.Mossberg500",			0.5,
			"Base.Mossberg500Tactical",			0.5,
			"Base.MP5",		0.5,
			"Base.Solvent",				1,
			},
		},
		locker = {
			rolls = 3,
			items = {
	      "Base.Sling", 5,
				"Base.Shotgun",		3,
				"Base.Mossberg500",			3,
				"Base.Mossberg500Tactical",			3,
				"Base.VarmintRifle",			2,
				"Base.AssaultRifle",			1,
				"Base.AmmoCan308",		0.5,
				"Base.AmmoCan9mm",		1,
				"Base.Solvent",				1,
			},
		},
		metal_shelves = {
			rolls = 3,
			items = {
				"Base.556Box",			1,
				"Base.4440Box",		1,
				"Base.762Box",		1,
				"Base.223Box",		1,
				"Base.308Box",		1,
				"Base.22LRBox",          5,
				"Base.Bullets38Box",		4,
				"Base.Bullets44Box",		3,
				"Base.Bullets45Box",		4,
				"Base.Bullets9mmBox",		4,
				"Base.ShotgunShellsBox",				5,
				"Base.AmmoCan308",		0.5,
				"Base.AmmoCan9mm",		1,
				"Base.Solvent",				1,
			},
		},
		crate = {
			rolls = 3,
			items = {
			"Base.Solvent",				1,
			},
		},
	},

	hunting = {
		counter = {
			rolls = 3,
			items = {
				"Base.ShotgunShellsBox",				5,
	      "Base.Sling", 5,
	      "Base.Sling_Leather",     5,
				"Base.Scope2x",				1,
				"Base.Scope4x",				1,
				"Base.Scope8x",				1,
				"Base.RedDot",				1,
				"Base.Rifle_Bipod",				1,
				"Base.RecoilPad",				1,
				"Base.ExtendedRecoilPad",				1,
				"Base.ShotgunStock",		1,
				"Base.TacticalStock",		1,
				"Base.LightShotgunStock",		1,
				"Base.AmmoStock",			1,
				"Base.AssaultRifle2", 		0.5,
				"Base.FN_FAL", 		1,
				"Base.FN_FAL_Mag", 		0.5,
				"Base.MP5_Stock_Detracted",				1,
				"Base.Rifle_Bipod",			1,
				"Base.GunToolKit",				1,
			},
		},
		displaycase = {
			rolls = 1,
			items = {
				"Base.DoubleBarrelShotgun",			2,
				"Base.Winchester94",			2,
				"Base.Winchester73",				2,
				"Base.GunToolKit",				1,
			},
		},
		locker = {
			rolls = 2,
			items = {
				"Base.DoubleBarrelShotgun",			2,
				"Base.Shotgun",		3,
				"Base.Mossberg500",			3,
				"Base.Mossberg500Tactical",			3,
				"Base.Winchester94",			2,
				"Base.Winchester73",				2,
				"Base.HuntingRifle",			3,
				"Base.Rugerm7722",			3,
				"Base.VarmintRifle",			2,
				"Base.AssaultRifle",			1,
				"Base.M16A2",					1,
				"Base.556Clip",		2,
				"Base.FN_FAL", 		1,
				"Base.FN_FAL_Mag", 		0.5,
				"Base.GunToolKit",				1,
			},
		},
		metal_shelves = {
			rolls = 3,
			items = {
				"Base.556Box",			1,
				"Base.4440Box",		1,
				"Base.762Box",		1,
				"Base.223Box",		1,
				"Base.308Box",		1,
				"Base.22LRBox",          5,
				"Base.Bullets38Box",		4,
				"Base.Bullets44Box",		3,
				"Base.Bullets45Box",		4,
				"Base.Bullets9mmBox",		4,
				"Base.ShotgunShellsBox",				5,
				"Base.AmmoCan762",		0.5,
				"Base.AmmoCan556",		0.5,
				"Base.AmmoCan308",		0.5,
				"Base.AmmoCan9mm",		1,
				"Base.GunToolKit",				1,
			},
		},
		crate = {
			rolls = 3,
			items = {
				"Base.AmmoCan762",		0.5,
				"Base.AmmoCan556",		0.5,
				"Base.AmmoCan308",		0.5,
				"Base.AmmoCan9mm",		1,
				"Base.GunToolKit",				1,
				"Base.Solvent",				1,
			},
		},
	},

	armysurplus = {
		counter = {
			rolls = 3,
			items = {
				"Base.Sling",				1,
				"Base.Scope2x",				1,
				"Base.Scope4x",				1,
				"Base.Scope8x",				1,
				"Base.RedDot",				1,
				"Base.Rifle_Bipod",				1,
				"Base.RecoilPad",				1,
				"Base.ExtendedRecoilPad",				1,
				"Base.ShotgunStock",		1,
				"Base.TacticalStock",		1,
				"Base.LightShotgunStock",		1,
				"Base.AmmoStock",			1,
				"Base.MP5_Stock_Detracted",				1,
				"Base.Rifle_Bipod",			1,
				"Base.556Clip",		2,
				"Base.FN_FAL_Mag", 		0.5,
				"Base.Glock17Mag",				1,
				"Base.UZIMag",          1,
				"Base.GunToolKit",				1,
				"Base.Solvent",				1,
			},
		},
		displaycase = {
			rolls = 3,
			items = {
				"Base.Shotgun",		3,
				"Base.Winchester94",			2,
				"Base.Winchester73",				2,
				"Base.VarmintRifle",			2,
				"Base.AssaultRifle",			1,
				"Base.M16A2",					1,
				"Base.556Clip",		2,
				"Base.FN_FAL", 		1,
				"Base.FN_FAL_Mag", 		0.5,
				"Base.ColtPeacemaker",				1,
				"Base.Pistol2",				1,
				"Base.45Clip",				1,
				"Base.Solvent",				1,
			},
		},
		locker = {
			rolls = 3,
			items = {
				"Base.DoubleBarrelShotgun",			2,
				"Base.Shotgun",		3,
				"Base.Mossberg500",			3,
				"Base.Mossberg500Tactical",			3,
				"Base.Winchester94",			2,
				"Base.Winchester73",				2,
				"Base.HuntingRifle",			3,
				"Base.Rugerm7722",			3,
				"Base.VarmintRifle",			2,
				"Base.M24Rifle",			1,
				"Base.AssaultRifle",			1,
				"Base.AssaultRifle2",					1,
				"Base.FN_FAL", 		1,
				"Base.FN_FAL_Mag", 		0.5,
				"Base.Solvent",				1,
			},
		},
		metal_shelves = {
			rolls = 3,
			items = {
				"Base.556Box",			1,
				"Base.4440Box",		1,
				"Base.762Box",		1,
				"Base.223Box",		1,
				"Base.308Box",		1,
				"Base.22LRBox",          5,
				"Base.Bullets38Box",		4,
				"Base.Bullets44Box",		3,
				"Base.Bullets45Box",		4,
				"Base.Bullets9mmBox",		4,
				"Base.ShotgunShellsBox",				5,
				"Base.AmmoCan762",		0.5,
				"Base.AmmoCan556",		0.5,
				"Base.AmmoCan308",		0.5,
				"Base.AmmoCan9mm",		1,
				"Base.Solvent",				1,
			},
		},
		crate = {
			rolls = 3,
			items = {
				"Base.AmmoCan762",		0.5,
				"Base.AmmoCan556",		0.5,
				"Base.AmmoCan308",		0.5,
				"Base.AmmoCan9mm",		1,
			},
		},
	},

	camping = {

		displaycase = {
			rolls = 3,
			items = {
				"Base.FN_FAL_Mag", 		0.5,
				"Base.UZIMag",          1,
				"Base.Glock17Mag",				1,
				"Base.556Clip",		2,
				"Base.Solvent",				1,
			},
		},
		locker = {
			rolls = 3,
			items = {
				"Base.DoubleBarrelShotgun",			2,
				"Base.Shotgun",		3,
				"Base.Mossberg500",			3,
				"Base.Mossberg500Tactical",			3,
				"Base.Winchester94",			2,
				"Base.Winchester73",				2,
				"Base.HuntingRifle",			3,
				"Base.Rugerm7722",			3,
				"Base.VarmintRifle",			2,
				"Base.M24Rifle",			1,
				"Base.AssaultRifle",			1,
				"Base.M16A2",					1,
				"Base.FN_FAL", 		1,
				"Base.UZI", 		0.5,
				"Base.Solvent",				1,
			},
		},
		metal_shelves = {
			rolls = 3,
			items = {
				"Base.556Box",			1,
				"Base.4440Box",		1,
				"Base.762Box",		1,
				"Base.223Box",		1,
				"Base.308Box",		1,
				"Base.22LRBox",          5,
				"Base.Bullets38Box",		4,
				"Base.Bullets44Box",		3,
				"Base.Bullets45Box",		4,
				"Base.Bullets9mmBox",		4,
				"Base.ShotgunShellsBox",				5,
				"Base.AmmoCan762",		0.5,
				"Base.AmmoCan556",		0.5,
				"Base.AmmoCan308",		0.5,
				"Base.AmmoCan9mm",		1,
				"Base.Solvent",				1,
			},
		},
		crate = {
			rolls = 3,
			items = {
				"Base.Solvent",				1,
				"Base.GunToolKit",				0.5,
			},
		},
	},

	toolstore = {
		shelves = {
			rolls = 3,
			items = {
				"Base.Solvent",				5,
			},
		},
		counter = {
			rolls = 2,
			items = {
				"Base.Solvent",				5,
			},
		},
	},

	bar = {
		counter = {
			rolls = 1,
			items = {
				"Base.ShotgunShellsBox",5,
				"Base.DoubleBarrelShotgun",			2,
				"Base.Shotgun",		3,
				"Base.Winchester94",			2,
				"Base.Winchester73",				2,
				"Base.Solvent",				2,
			},
		},
	},
	zippeestore = {
		counter = {
			rolls = 1,
			items = {
			},
			fillRand=3,
		},
	},
	gigamart = {
		counter = {
			rolls = 1,
			items = {
				"Base.Solvent",				1,
			},
		},
	},
	fossoil = {
		counter = {
			rolls = 1,
			items = {
				"Base.Solvent",				1,
			},
		},
	},
	loggingfactory = {
		counter = {
			rolls = 1,
			items = {
						"Base.Solvent",				1,
			},
		},
		crate = {
			rolls = 1,
			items = {
			},
		},
	},
	toystore = {
		counter = {
			rolls = 1,
			items = {
			},
		},
		shelves = {
			rolls = 1,
			items = {
			},
		},
	},

	bedroom = {
		sidetable = {
			rolls = 1,
			items = {
				"Base.Civilian_Small",	0.01,
			},
		},
		all = {
			rolls = 1,
			items = {
				"Base.Civilian_Small",		0.01,
				"Base.Hunting",	0.01,
			},
		},
	},
	garagestorage = {
		other = {
			rolls = 2,
			items = {
				"Base.Civilian_Small", 0.2,
				"Base.Hunting",		0.1,
			},
		},
	},
	garage = {
		metal_shelves = {
			rolls = 2,
			items = {
				"Base.Civilian_Small",	0.2,
				"Base.Hunting",	0.1,
				"Base.Solvent",				0.5,
			},
		},
	},
	shed = {
		metal_shelves = {
			rolls = 2,
			items = {
				"Base.Solvent",				1,
			},
		},
	},
	farmstorage = {
		locker = {
			rolls = 3,
			items = {
				"Base.Civilian_Small",		0.2,
				"Base.Hunting",		0.1,
				"Base.GunToolKit",				1,
			},
		},
		all = {
			rolls = 1,
			items = {
				"Base.Civilian_Small",		0.2,
				"Base.Hunting",		0.1,
				"Base.Solvent",				0.1,
			},
		},
	},
	gasstorage = {
		all = {
			rolls = 1,
			items = {
				"Base.Solvent",				1,
			},
		},
	},
	mechanic = {
		all = {
			rolls = 1,
			items = {
				"Base.Solvent",				5,
			},
		},
	},
	storageunit = {

		locker = {
			rolls = 3,
			items = {
				"Base.45Silencer",			0.2,
				"Base.9mmSilencer",			0.25,
				"Base.223Silencer",			0.15,
				"Base.308Silencer",			0.15,
				"Base.Solvent",				1,
			},
		},

		all ={
			rolls = 1,
			items = {
				"Base.Civilian_Small",			0.1,
				"Base.Hunting",			0.1,
				"Base.LawEnforcement",			0.1,
			},
		},
--		metal_shelves ={
--			rolls = 1,
--			items = {
--
--			},
--		},
	},

	Guitarcase = {
		rolls = 1,
		items = {
		},
	},

	Toolbox = {
		rolls = 1,
		items = {
		},
	},

	Bag_Schoolbag = {
		rolls = 1,
		items = {
		},
	},

	Bag_WeaponBag = {
		rolls = 3,
		items = {
		},
	},

	Bag_SurvivorBag = {
		rolls = 1,
		items = {
			"Base.HuntingRifle",			3,
			"Base.Rugerm7722",			3,
			"Base.VarmintRifle",			2,
			"Base.M24Rifle",			1,
			"Base.AssaultRifle",			1,
			"Base.M16A2",					1,
			"Base.556Clip",		2,
			"Base.556Box",			1,
			"Base.762Box",		2,
			"Base.223Box",		2,
			"Base.308Box",		2,
			"Base.22LRBox",          5,
		},
	},

	ShotgunCache1 = {
		ShotgunBox = {
			rolls = 1,
			items = {
				"Base.DoubleBarrelShotgun",			2,
				"Base.Shotgun",		3,
				"Base.Mossberg500",			3,
				"Base.Mossberg500Tactical",			3,
				"Base.Winchester94",			2,
				"Base.Winchester73",				2,
			}
		},
		Bag_DuffelBagTINT = {
			rolls = 1,
			items = {
				"Base.DoubleBarrelShotgun",			2,
				"Base.Shotgun",		3,
				"Base.Mossberg500",			3,
				"Base.Mossberg500Tactical",			3,
				"Base.Winchester94",			2,
				"Base.Winchester73",				2,
			},
		},
	},

	ShotgunCache2 = {
		ShotgunBox = {
			rolls = 1,
			items = {
				"Base.DoubleBarrelShotgun",			2,
				"Base.Shotgun",		3,
				"Base.Mossberg500",			3,
				"Base.Mossberg500Tactical",			3,
				"Base.Winchester94",			2,
				"Base.Winchester73",				2,
			}
		},
		counter = {
			rolls = 1,
			items = {
				"Base.DoubleBarrelShotgun",			2,
				"Base.Shotgun",		3,
				"Base.Mossberg500",			3,
				"Base.Mossberg500Tactical",			3,
				"Base.Winchester94",			2,
				"Base.Winchester73",				2,
			},
		},
	},

	GunCache1 = {
		GunBox = {
			rolls = 1,
			items = {
			},
		dontSpawnAmmo = true,
		},
		counter = {
			rolls = 1,
			items = {
			},
		},
		Bag_DuffelBagTINT = {
			rolls = 1,
			items = {
				"Base.DoubleBarrelShotgun",			2,
				"Base.Shotgun",		3,
				"Base.Mossberg500",			3,
				"Base.Mossberg500Tactical",			3,
				"Base.Winchester94",			2,
				"Base.Winchester73",				2,
			},
		},
	},

	GunCache2 = {
		GunBox = {
			rolls = 1,
			items = {
				"Base.Revolver",				1,
				"Base.Revolver_Long",				1,
				"Base.Revolver_Short",				1,
				"Base.Shotgun",				1,
				"Base.DoubleBarrelShotgun",				1,
				"Base.Remington870Wood",				1,
				"Base.Mossberg500",			0.5,
				"Base.Mossberg500Tactical",			0.5,
				"Base.UZI", 		0.5,
				"Base.MP5",		0.5,
				"Base.Winchester94", 				0.5,
				"Base.Winchester73",			0.5,
			},
		},
		Bag_DuffelBagTINT = {
			rolls = 1,
			items = {
				"Base.Revolver",				1,
				"Base.Revolver_Long",				1,
				"Base.Revolver_Short",				1,
				"Base.Shotgun",				1,
				"Base.DoubleBarrelShotgun",				1,
				"Base.Remington870Wood",				1,
				"Base.Mossberg500",			0.5,
				"Base.Mossberg500Tactical",			0.5,
				"Base.UZI", 		0.5,
				"Base.UZIMag", 		0.5,
				"Base.FN_FAL", 		0.5,
				"Base.FN_FAL_Mag", 		0.5,
				"Base.MP5",		0.5,
				"Base.Winchester94", 				0.5,
				"Base.Winchester73",			0.5,
			},
		},
	},
}

table.insert(Distributions, 1, distributionTable);

--for mod compat:
--SuburbsDistributions = distributionTable;
